name: Build

on: [push, pull_request]

jobs:

  build_wheels:
    name: Build wheels on windows-latest
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.0.0a2
 
      - name: Build wheels          
        env:
          CIBW_BUILD: cp38
          CIBW_BUILD_VERBOSITY: 3
        run: |
          python -m cibuildwheel --output-dir wheelhouse
          
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
          
      - name: Collect output
        run:  |
          ls -l
        #tar zcf wheels.tar.gz ./wheelhouse/
        #ls ./wheelhouse/
          
