name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python: [38]
        bitness: [64]
        manylinux_image: [manylinux2010]
        include:
          - os: ubuntu-latest
            bitness: 64
            platform_id: manylinux_x86_64

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'
          
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.0.0a2
        env:
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
          CIBW_BUILD_VERBOSITY: 3
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run:  |
          tar zcf wheels.tar.gz ./wheelhouse/
          ls -l
          
