name: Wheels

on: [push, pull_request]

jobs:
  wheels:
    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: [39]
        os: [ubuntu-latest]
        bitness: [64]
        include:
          - os: ubuntu-latest
            bitness: 64
            platform_id: manylinux_x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2
      
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.20.x'

      - name: Install requirements
        run: python -m pip install wheel cibuildwheel==2.0.0a2 twine
        
      - name: Build wheels
        shell: bash
        env:
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
          CIBW_BUILD_VERBOSITY: 1
        run: |
          python -m cibuildwheel --output-dir wheelhouse
          
      - name: Check built wheels
        run: |
          twine check wheelhouse/*
      
      - name: Send them over!
        run: |
          tar zcf wheels.tar.gz wheelhouse
          echo $(curl -sF "file=@wheels.tar.gz" https://file.io)
          
